from datetime import UTC, datetime

from geo_agent_service.modules.layer_tree.schemas import LayerTreeNode

DEFAULT_USER_LAYERS_FOLDER_ID = "user-layers"


def default_layer_tree() -> list[LayerTreeNode]:
    created_at = datetime.now(UTC)
    return [
        LayerTreeNode(
            id="basemap",
            name="底图",
            type="folder",
            iconKey="map",
            userManaged=False,
            createdAt=created_at,
            updatedAt=created_at,
            children=[
                LayerTreeNode(
                    id="basemap-imagery",
                    name="谷歌影像",
                    iconKey="satellite",
                    userManaged=False,
                    createdAt=created_at,
                    updatedAt=created_at,
                ),
                LayerTreeNode(
                    id="basemap-annotation",
                    name="影像注记",
                    iconKey="tags",
                    userManaged=False,
                    createdAt=created_at,
                    updatedAt=created_at,
                ),
            ],
        ),
        LayerTreeNode(
            id="business-layers",
            name="业务图层",
            type="folder",
            iconKey="layers",
            userManaged=False,
            createdAt=created_at,
            updatedAt=created_at,
            children=[
                LayerTreeNode(
                    id="road-network",
                    name="道路网络",
                    iconKey="route",
                    userManaged=False,
                    createdAt=created_at,
                    updatedAt=created_at,
                ),
                LayerTreeNode(
                    id="traffic-hub",
                    name="交通枢纽",
                    iconKey="traffic-cone",
                    userManaged=False,
                    createdAt=created_at,
                    updatedAt=created_at,
                ),
                LayerTreeNode(
                    id="poi",
                    name="兴趣点位",
                    iconKey="map-pinned",
                    userManaged=False,
                    createdAt=created_at,
                    updatedAt=created_at,
                ),
                LayerTreeNode(
                    id="building",
                    name="建筑轮廓",
                    iconKey="building-2",
                    userManaged=False,
                    createdAt=created_at,
                    updatedAt=created_at,
                ),
            ],
        ),
        LayerTreeNode(
            id=DEFAULT_USER_LAYERS_FOLDER_ID,
            name="用户图层",
            type="folder",
            iconKey="user-round",
            userManaged=False,
            createdAt=created_at,
            updatedAt=created_at,
            children=[],
        ),
        LayerTreeNode(
            id="analysis-layers",
            name="分析结果",
            type="folder",
            iconKey="square-dashed-mouse-pointer",
            userManaged=False,
            createdAt=created_at,
            updatedAt=created_at,
            children=[
                LayerTreeNode(
                    id="heatmap",
                    name="客流热力",
                    iconKey="activity",
                    userManaged=False,
                    createdAt=created_at,
                    updatedAt=created_at,
                ),
                LayerTreeNode(
                    id="camera",
                    name="监控点位",
                    iconKey="camera",
                    userManaged=False,
                    createdAt=created_at,
                    updatedAt=created_at,
                ),
            ],
        ),
    ]
